config/routes.rb
Rails.application.routes.draw do
  # get 'items/index'
  # get 'items/show'
  # get 'items/new'
  # get 'items/edit'
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    # show data
    @item = Item.find(params[:id])

  end

  def new
    @item = Item.new
  end

  def create
    item = Item.create(params.require(:item).permit(:name, :price))

    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(params.require(:item).permit(:name, :price))

    redirect_to items_path
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy

    redirect_to items_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h3>Edit Item</h3>
<%= form_with model: @item ,method: :patch do |form| %>
  <%= form.text_field :name, placeholder: "name" ,values: @item.name%>
  <%= form.text_field :price, placeholder: "price" %>
  <%= form.submit %>
<% end %>

app/views/items/index.html.erb
<h1> Items </h1>
<table>
  <thead>
    <tr>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <%# show %>
        <td><%= link_to 'Show', item %></td>
        <%# //delete %>
        <td><%= button_to "Delete", item_path(item), method: :delete, data: { confirm: "Are you sure?" } %></td>
        <%# //edit %>
        <td><%= link_to "Edit", edit_item_path(item) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<a href="/items/new">New Item</a>

app/views/items/new.html.erb
<h3>Create an Item</h3>
<%= form_with model: @item do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :price, placeholder: "price" %>
  <%= form.submit %>
<% end %>

app/views/items/show.html.erb
<h1>Item Show</h1>

<%# nampilin item %>
<p>Item Name : <%= @item.name %></p>
<p>Item Price : <%= @item.price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>